[AP] Moved state machine to async
GamedevExperienceStables/gamedev-experience-stables pull request #42
Opened 2023-01-30 21:31 UTC by Rezonanzo

2023-01-30 21:45 UTC, Rezonanzo commented
Будем ли мы все названия асинхронных методов жестко соблюдать и называть с Async в конце?

2023-01-31 07:15 UTC, ailuh requested changes
Reviewed

2023-01-31 07:16 UTC, ailuh approved these changes

2023-01-31 07:16 UTC, ailuh commented
Я не думаю что везде Async стоит добавлять, потому что не везде это выглядит логично

2023-01-31 07:18 UTC, ailuh commented
OnEnterAsync, EnterStateAsync мне кажется звучит так себе

2023-01-31 10:00 UTC, merged