[AA] Spawn system
GamedevExperienceStables/gamedev-experience-stables pull request #49
Opened 2023-02-02 19:01 UTC by Astashevich

2023-02-02 19:15 UTC, Rezonanzo requested changes

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            //_enemies.Add(enemyInstance);
не оставляй закомментированный код

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            if (spawnCount <= 0) return;
если соблюдать общий стиль, то у нас везде return перекидывается на новую строчку

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            if (_timeSinceLastSpawn >= spawnInterval) _timeSinceLastSpawn = 0f;
это тоже на новую строчку

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +            if (spawnCounts <= 0) return;
новая строка

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +        private float respawnTimerS = 0f;
сейчас подумал, что все-таки имеет смысл писать величины только, если используются отличные от секунд, а так по умолчанию всегда секунды. Убери, все-таки S, чтобы не создавать лишнего.

2023-02-02 19:15 UTC, Rezonanzo commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +            //if (!_isTimerEnds) return;
не оставляй закомментированный код

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            if (_timeSinceLastSpawn >= spawnInterval) _timeSinceLastSpawn = 0f;
Fixed

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            if (spawnCount <= 0) return;
Fixed

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnPoint.cs
> +            //_enemies.Add(enemyInstance);
Fixed

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +            if (spawnCounts <= 0) return;
Fixed

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +        private float respawnTimerS = 0f;
Fixed

2023-02-03 10:56 UTC, Astashevich commented on Assets/Game/Scripts/Enemies/EnemySpawnZone.cs
> +            //if (!_isTimerEnds) return;
Deleted

2023-02-03 11:28 UTC, Rezonanzo approved these changes

2023-02-03 11:47 UTC, merged